export const StudentData = [
  {
    id: 1234567,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@bears.shawu.edu",
    phone: "(686) 758-7589",
    classification: "Junior",
    gpa: 3.5,
  },
  {
    id: 9876543,
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Senior",
    gpa: 3.9,
  },
  {
    id: 6543210,
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Sophomore",
    gpa: 3.2,
  },
  {
    id: 2345678,
    firstName: "Emily",
    lastName: "Davis",
    email: "emily.davis@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Freshman",
    gpa: 3.7,
  },
  {
    id: 8769432,
    firstName: "Daniel",
    lastName: "Brown",
    email: "daniel.brown@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Senior",
    gpa: 3.8,
  },
  {
    id: 3496789,
    firstName: "Sarah",
    lastName: "Wilson",
    email: "sarah.wilson@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Junior",
    gpa: 3.4,
  },
  {
    id: 7654321,
    firstName: "David",
    lastName: "Lee",
    email: "david.lee@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Sophomore",
    gpa: 3.1,
  },
  {
    id: 4567890,
    firstName: "Olivia",
    lastName: "Taylor",
    email: "olivia.taylor@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Junior",
    gpa: 3.6,
  },
  {
    id: 6541234,
    firstName: "James",
    lastName: "Miller",
    email: "james.miller@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Senior",
    gpa: 3.9,
  },
  {
    id: 9874321,
    firstName: "Sophia",
    lastName: "Johnson",
    email: "sophia.johnson@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Freshman",
    gpa: 3.2,
  },
  {
    id: 1238765,
    firstName: "Liam",
    lastName: "Anderson",
    email: "liam.anderson@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Sophomore",
    gpa: 3.3,
  },
  {
    id: 8765432,
    firstName: "Chloe",
    lastName: "Martin",
    email: "chloe.martin@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Junior",
    gpa: 3.7,
  },
  {
    id: 5678901,
    firstName: "William",
    lastName: "Moore",
    email: "william.moore@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Senior",
    gpa: 3.8,
  },
  {
    id: 4321098,
    firstName: "Ava",
    lastName: "White",
    email: "ava.white@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Freshman",
    gpa: 3.6,
  },
  {
    id: 3455789,
    firstName: "Ethan",
    lastName: "Davis",
    email: "ethan.davis@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Sophomore",
    gpa: 3.0,
  },
  {
    id: 7890123,
    firstName: "Mia",
    lastName: "Wilson",
    email: "mia.wilson@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Junior",
    gpa: 3.5,
  },
  {
    id: 2345678,
    firstName: "Noah",
    lastName: "Johnson",
    email: "noah.johnson@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Senior",
    gpa: 3.9,
  },
  {
    id: 8901234,
    firstName: "Emma",
    lastName: "Smith",
    email: "emma.smith@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Freshman",
    gpa: 3.2,
  },
  {
    id: 4561234,
    firstName: "Liam",
    lastName: "Davis",
    email: "liam.davis@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Sophomore",
    gpa: 3.1,
  },
  {
    id: 7654321,
    firstName: "Olivia",
    lastName: "Miller",
    email: "olivia.miller@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Junior",
    gpa: 3.7,
  },
  {
    id: 6789012,
    firstName: "James",
    lastName: "Martin",
    email: "james.martin@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Senior",
    gpa: 3.8,
  },
  {
    id: 8901234,
    firstName: "Sophia",
    lastName: "Anderson",
    email: "sophia.anderson@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Freshman",
    gpa: 3.6,
  },
  {
    id: 5432109,
    firstName: "Benjamin",
    lastName: "Brown",
    email: "benjamin.brown@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Sophomore",
    gpa: 3.3,
  },
  {
    id: 1239876,
    firstName: "Emily",
    lastName: "Taylor",
    email: "emily.taylor@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Junior",
    gpa: 3.7,
  },
  {
    id: 4321098,
    firstName: "Daniel",
    lastName: "Smith",
    email: "daniel.smith@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Senior",
    gpa: 3.8,
  },
  {
    id: 6789012,
    firstName: "Ava",
    lastName: "Wilson",
    email: "ava.wilson@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Freshman",
    gpa: 3.6,
  },
  {
    id: 5432109,
    firstName: "Liam",
    lastName: "Moore",
    email: "liam.moore@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Sophomore",
    gpa: 3.2,
  },
  {
    id: 2348765,
    firstName: "Chloe",
    lastName: "Davis",
    email: "chloe.davis@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Junior",
    gpa: 3.4,
  },
  {
    id: 9876543,
    firstName: "Ethan",
    lastName: "Johnson",
    email: "ethan.johnson@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Senior",
    gpa: 3.9,
  },
  {
    id: 6789012,
    firstName: "Mia",
    lastName: "Smith",
    email: "mia.smith@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Freshman",
    gpa: 3.1,
  },
  {
    id: 3456789,
    firstName: "Noah",
    lastName: "Davis",
    email: "noah.davis@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Sophomore",
    gpa: 3.6,
  },
  {
    id: 8901234,
    firstName: "Emma",
    lastName: "Wilson",
    email: "emma.wilson@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Junior",
    gpa: 3.7,
  },
  {
    id: 2345678,
    firstName: "James",
    lastName: "Johnson",
    email: "james.johnson@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Senior",
    gpa: 3.8,
  },
  {
    id: 5678901,
    firstName: "Sophia",
    lastName: "Davis",
    email: "sophia.davis@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Freshman",
    gpa: 3.2,
  },
  {
    id: 4561234,
    firstName: "William",
    lastName: "Martin",
    email: "william.martin@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Sophomore",
    gpa: 3.3,
  },
  {
    id: 1239876,
    firstName: "Ava",
    lastName: "Moore",
    email: "ava.moore@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Junior",
    gpa: 3.7,
  },
  {
    id: 4321098,
    firstName: "Benjamin",
    lastName: "Wilson",
    email: "benjamin.wilson@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Senior",
    gpa: 3.9,
  },
  {
    id: 8901234,
    firstName: "Olivia",
    lastName: "Smith",
    email: "olivia.smith@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Freshman",
    gpa: 3.4,
  },
  {
    id: 5432109,
    firstName: "Daniel",
    lastName: "Davis",
    email: "daniel.davis@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Sophomore",
    gpa: 3.1,
  },
  {
    id: 1239876,
    firstName: "Chloe",
    lastName: "Wilson",
    email: "chloe.wilson@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Junior",
    gpa: 3.6,
  },
  {
    id: 4561234,
    firstName: "Liam",
    lastName: "Martin",
    email: "liam.martin@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Senior",
    gpa: 3.8,
  },
  {
    id: 2348765,
    firstName: "Emily",
    lastName: "Smith",
    email: "emily.smith@bears.shawu.edu",
    phone: "(779) 978-8767",
    classification: "Freshman",
    gpa: 3.5,
  },
];
